- # @see https://galaxy.ansible.com/chusiang/switch-apt-mirror/
  src: chusiang.switch-apt-mirror
  path: roles/

- # @see https://galaxy.ansible.com/chusiang/vim-and-vi-mode/
  src: chusiang.vim-and-vi-mode
  path: roles/
