#!/usr/bin/env ansible-playbook
# ============================================================
#  Author: Chu-Siang Lai / chusiang (at) drx.tw
#  Blog: http://note.drx.tw
#  Filename: setup_server.yml
#  Modified: 2017-08-01 21:54
#  Description: Setup my Ubuntu Server with Ansible.
# ============================================================

---
- name: setup server
  hosts: local

  roles:
    - chusiang.switch-apt-mirror
    - chusiang.vim-and-vi-mode

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  tasks:
    # server
    - name: include config_server.yml
      include: tasks/config_server.yml
      tags:
        - server

    - name: include config_server.yml
      include: tasks/config_server.yml
      tags:
        - server

# vim: ft=ansible :
