---

- name: switch the default Input Method to hime
  command: im-config -n hime

- name: configure the terminator
  copy:
    src: files/terminator.conf
    dest: "{{ ansible_user_dir }}/.config/terminator/config"

- name: configure the zeal
  copy:
    src: files/zeal.conf
    dest: "{{ ansible_user_dir }}/.config/Zeal/Zeal.conf"

# vim: ft=ansible :
