---

# Gcin
- name: switch the default Input Method
  command: im-config -n gcin

- name: check boshiamy-gcin tmp path
  stat: path=/tmp/boshiamy-gcin
  register: boshiamy_gcin_tmp_path
  tags: gcin

- name: check boshiamy-gcin zipfile path
  stat: path={{ gcin_liu_table_path }}
  register: boshiamy_gcin_zipfile_path
  tags: gcin

- name: unzip the boshiamy-gcin.tar.gz
  unarchive:
    src: "{{ gcin_liu_table_path }}"
    dest: /tmp/
  when:
    - boshiamy_gcin_tmp_path.stat.exists != true
    - boshiamy_gcin_zipfile_path.stat.exists == true
  tags: gcin

- name: import the liu table of gcin
  copy:
    src: /tmp/boshiamy-gcin/boshiamy-t.gtab
    dest: "{{ ansible_user_dir }}/.gcin/noseeing.gtab"
  when: boshiamy_gcin_tmp_path.stat.exists == true
  tags: gcin

- name: import the liu png of gcin
  copy:
    src: /tmp/boshiamy-gcin/boshiamy-t.png
    dest: "{{ ansible_user_dir }}/.gcin/noseeing.png"
  when: boshiamy_gcin_tmp_path.stat.exists == true
  tags: gcin

- name: configure the terminator
  copy:
    src: files/terminator.conf
    dest: "{{ ansible_user_dir }}/.config/terminator/config"

- name: configure the zeal
  copy:
    src: files/zeal.conf
    dest: "{{ ansible_user_dir }}/.config/Zeal/Zeal.conf"

# vim: ft=ansible :
