---

# Gcin.
- name: switch the default Input Method
  command: im-config -n gcin

- name: check boshiamy-gcin tmp path
  stat: path=/tmp/boshiamy-gcin
  register: boshiamy_gcin_tmp_path
  tags: gcin

- name: check boshiamy-gcin zipfile path
  stat: path={{ gcin_liu_table_path }}
  register: boshiamy_gcin_zipfile_path
  tags: gcin

- name: unzip the boshiamy-gcin.tar.gz
  unarchive:
    src: "{{ gcin_liu_table_path }}"
    dest: /tmp/
  when:
    - boshiamy_gcin_tmp_path.stat.exists != true
    - boshiamy_gcin_zipfile_path.stat.exists == true
  tags: gcin

- name: import the liu table of gcin
  copy:
    src: /tmp/boshiamy-gcin/boshiamy-t.gtab
    dest: "{{ ansible_user_dir }}/.gcin/noseeing.gtab"
  when: boshiamy_gcin_tmp_path.stat.exists == true
  tags: gcin

#- name: import the liu png of gcin
#  copy:
#    src: /tmp/boshiamy-gcin/boshiamy-t.png
#    dest: "{{ ansible_user_dir }}/.gcin/noseeing.png"
#  when: boshiamy_gcin_tmp_path.stat.exists == true
#  tags: gcin

- name: import the configs of gcin
  copy:
    src: "files/gcin/{{ item }}"
    dest: "{{ ansible_user_dir }}/.gcin/{{ item }}"
  with_items: "{{ gcin_config_files }}"
  tags: gcin

# Setting the Monospace font with LiHei Pro + Monaco.
- name: create the fonts directory
  file:
    path: "{{ ansible_user_dir }}/.fonts"
    state: directory
    mode: 0755
  tags: font

- name: get the font files
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.fonts"
  with_items:
    - "http://site.drx.tw/software/fonts/LiHeiProPC.ttf"
    - "http://site.drx.tw/software/fonts/monaco.ttf"
  tags: font

- name: copy the fonts.conf
  copy:
    src: files/fonts.conf
    dest: "{{ ansible_user_dir }}/.fonts.conf"
  tags: font

# Terminator.
- name: configure the terminator
  copy:
    src: files/terminator.conf
    dest: "{{ ansible_user_dir }}/.config/terminator/config"

# Zeal.
- name: configure the zeal
  copy:
    src: files/zeal.conf
    dest: "{{ ansible_user_dir }}/.config/Zeal/Zeal.conf"

# vim: ft=ansible :
