---

- name: switch the default Input Method to hime
  command: im-config -n hime

- name: configure the terminator
  copy:
    src: files/terminator.cfg
    dest: "{{ ansible_user_dir }}/.config/terminator/config"

# vim: ft=ansible :
