---

# Ubuntu

# - server
- name: include setup ubuntu server task
  include: setup_ubuntu_server.yml
  tags:
    - server
  when: ansible_pkg_mgr == "apt"

- name: include config ubuntu server task
  include: config_ubuntu_server.yml
  tags:
    - server
  when: ansible_pkg_mgr == "apt"

# - desktop
- name: include setup ubuntu desktop task
  include: setup_ubuntu_desktop.yml
  tags:
    - desktop
  when: ansible_pkg_mgr == "apt"

- name: include config ubuntu desktop task
  include: config_ubuntu_desktop.yml
  tags:
    - desktop
  when: ansible_pkg_mgr == "apt"

# CentOS
- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present
  when: ansible_pkg_mgr == "yum"

#- name: delegate to SELINUX handling subtask, if necessary
#  include: set-selinux.yml
#  when: php_in_selinux is defined and php_in_selinux == true

- name: include setup centos server task
  include: setup_centos_server.yml
  when: ansible_pkg_mgr == "yum"


# vim: ft=ansible :
