---

# Accept license of ttf-mscorefonts-installer.
- name: 'accept ttf-mscorefonts-installer license'
  become: true
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    value: true
    vtype: select

- name: install apt packages of desktop
  become: true
  apt: name={{ apt_desktop_packages }} state=present

- name: install language packages with apt
  become: true
  apt: name={{ item }} state=present
  with_items:
    - language-pack-gnome-zh-hant
    - language-pack-zh-hant
    - libreoffice-l10n-zh-tw
    - libreoffice-help-zh-tw
    - thunderbird-locale-zh-tw

# Zeal.
- name: add apt key of zeal
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: 786285426B130F8C8C67CEF87F73D5BEFC1B6133

- name: add apt repository of zeal
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/zeal-developers/ppa/ubuntu {{ ansible_distribution_release }} main"

    state: present

# NixNote2.
- name: add apt key of nixnote
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: AF3D90CFFDB12616A844CD229A66B34BAF11ADDE

- name: add apt repository of nixnote
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu {{ ansible_distribution_release }} main"
    state: present

# WineHQ.
- name: add apt key of winehq 
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: B59525092DF44DD0CE1D5D47E61A24DF77C899CB

- name: add apt repository of winehq
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/wine/wine-builds/ubuntu {{ ansible_distribution_release }} main"
    state: present

#- name: enable 32 bit architecture of dpkg
#  become: true
#  lineinfile:
#    path: /var/lib/dpkg/arch
#    line: "i386"
#    state: present

- name: install apt packages of desktop with ppa
  become: true
  apt: name={{ item }} state=present
  with_items:
    - nixnote2
    - winehq-staging
    - zeal

# Franz
- name: get the franz tarball file
  get_url:
    url: "{{ franz_tarball_url }}"
    dest: "/tmp/franz-linux-x64.tgz"
  tags: franz

- name: create the franz directory
  become: true
  file:
    path: "/opt/franz"
    state: directory
    mode: 0755
  tags: franz

- name: check the franz binary target
  stat: path=/opt/franz/Franz
  register: franz_target_path
  tags: franz

- name: unarchive the franz tarball
  become: true
  unarchive:
    src: "/tmp/franz-linux-x64.tgz"
    dest: "/opt/franz/"
  when: franz_target_path.stat.exists != true
  tags: franz

- name: copy the franz icon
  copy:
    src: files/franz.png
    dest: "{{ ansible_user_dir }}/.local/share/icons/"
  tags: franz

- name: copy the franz.desktop
  copy:
    src: files/franz.desktop
    dest: "{{ ansible_user_dir }}/.local/share/applications/"
  tags: franz

# vim: ft=ansible :
