---

# Accept license of ttf-mscorefonts-installer.
- name: 'accept ttf-mscorefonts-installer license'
  become: true
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    value: true
    vtype: select
  tags: wine

- name: install apt packages of desktop
  become: true
  apt: name={{ apt_desktop_packages }} state=present

- name: install language packages with apt
  become: true
  apt: name={{ item }} state=present
  with_items:
    - language-pack-gnome-zh-hant
    - language-pack-zh-hant
    - libreoffice-l10n-zh-tw
    - libreoffice-help-zh-tw
    - thunderbird-locale-zh-tw

# Dropbox
- name: add apt key of dropbox
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
  tags: dropbox

- name: add apt repository of dropbox
  become: true
  apt_repository:
    repo: "deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main"
    state: present
  tags: dropbox

# Zeal.
- name: add apt key of zeal
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: 786285426B130F8C8C67CEF87F73D5BEFC1B6133
  tags: zeal

- name: add apt repository of zeal
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/zeal-developers/ppa/ubuntu {{ ansible_distribution_release }} main"
    state: present
  tags: zeal

# NixNote2.
- name: add apt key of nixnote2
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: AF3D90CFFDB12616A844CD229A66B34BAF11ADDE
  tags: nixnote2

- name: add apt repository of nixnote2
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu {{ ansible_distribution_release }} main"
    state: present
  tags: nixnote2

# WineHQ.
- name: add apt key of winehq 
  become: true
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: B59525092DF44DD0CE1D5D47E61A24DF77C899CB
  tags: wine

- name: add apt repository of winehq
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/wine/wine-builds/ubuntu {{ ansible_distribution_release }} main"
    state: present
  tags: wine

- name: enable 32 bit architecture of dpkg
  become: true
  lineinfile:
    dest: /var/lib/dpkg/arch
    line: "i386"
    state: present
  tags: wine

- name: install third-party apt packages of desktop
  become: true
  apt: name={{ item }} state=present
  with_items:
    - dropbox
    - nixnote2
    - winehq-staging
    - zeal

# Franz
- name: get the franz tarball file
  get_url:
    url: "{{ franz_tarball_url }}"
    dest: "/tmp/franz-linux-x64.tgz"
  tags: franz

- name: create the franz directory
  become: true
  file:
    path: "/opt/franz"
    state: directory
    mode: 0755
  tags: franz

- name: check the franz binary file state
  stat: path=/opt/franz/Franz
  register: franz_target_path
  tags: franz

- name: unarchive the franz tarball
  become: true
  unarchive:
    src: "/tmp/franz-linux-x64.tgz"
    dest: "/opt/franz/"
  when: franz_target_path.stat.exists != true
  tags: franz

- name: copy the franz icon
  become: true
  copy:
    src: files/franz.png
    dest: "/usr/share/icons/"
  tags: franz

- name: copy the franz.desktop
  become: true
  copy:
    src: files/franz.desktop
    dest: "/usr/share/applications/"
  tags: franz

# FreeMind
- name: get the freemind tarball file
  get_url:
    url: "{{ freemind_tarball_url }}"
    dest: "/tmp/freemind.zip"
  tags: freemind

- name: create the freemind directory
  become: true
  file:
    path: "/opt/freemind"
    state: directory
    mode: 0755
  tags: freemind

- name: check the freemind execute file state
  stat: path=/opt/freemind/freemind.sh
  register: freemind_target_path
  tags: freemind

- name: unarchive the freemind tarball
  become: true
  unarchive:
    src: "/tmp/freemind.zip"
    dest: "/opt/freemind/"
  when: freemind_target_path.stat.exists != true
  tags: freemind

- name: add execute permission of freemind.sh
  become: true
  file:
    path: /opt/freemind/freemind.sh
    mode: 0755
  tags: freemind

- name: copy the freemind icon
  become: true
  copy:
    src: files/freemind.png
    dest: "/usr/share/icons/"
  tags: freemind

- name: copy the freemind.desktop
  become: true
  copy:
    src: files/freemind.desktop
    dest: "/usr/share/applications/"
  tags: freemind

# vim: ft=ansible :
