---

- name: install apt packages for desktop
  become: true
  apt: name={{ item }} state=present
  with_items:
    - vim-gnome
    - terminator
    - shutter
    - workrave
    - sm
    - vlc
    - gcin
    - chromium-browser
    - compizconfig-settings-manager

- name: install language packages with apt
  become: true
  apt: name={{ item }} state=present
  with_items:
    - language-pack-gnome-zh-hant
    - language-pack-zh-hant
    - libreoffice-l10n-zh-tw
    - libreoffice-help-zh-tw
    - thunderbird-locale-zh-tw

# Zeal.
- name: add apt key of zeal
  become: true
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 786285426B130F8C8C67CEF87F73D5BEFC1B6133

- name: add apt repository of zeal
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/zeal-developers/ppa/ubuntu {{ ansible_distribution_release }} main"

    state: present

- name: install the zeal with ppa repo
  become: true
  apt:
    name: zeal
    state: present

# NixNote 2.
- name: add apt key of nixnote
  become: true
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: AF3D90CFFDB12616A844CD229A66B34BAF11ADDE

- name: add apt repository of nixnote
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: install the nixnote with ppa repo
  become: true
  apt:
    name: nixnote2
    state: present

# WineHQ.
- name: add apt key of winehq 
  become: true
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: B59525092DF44DD0CE1D5D47E61A24DF77C899CB

- name: add apt repository of winehq
  become: true
  apt_repository:
    repo: "deb http://ppa.launchpad.net/wine/wine-builds/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: enable 32 bit architecture of dpkg
  lineinfile:
    path: /var/lib/dpkg/arch
    line: 'i386'

- name: install the winehq with ppa repo
  become: true
  apt:
    name: winehq-staging
    state: present



# vim: ft=ansible :
